language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt --extra-index-url file://$PWD/lib --upgrade  --ignore-installed six
  - pip install -r test-requirements.txt
# command to run tests
script:
  - ./make-work
  - pycodestyle samples tests
  - pytest


deploy:
  provider: pypi
  user: '__token__'
  password:
    secure: ZaiNDxtDvVeievOhv6m/ZaecRhkpXG7IkumzmWJDmS87FDjn2V/ipOL1+o33i8YwLPaZXEcYXhQUn6xNAQ4R/UO8bftkbcBH6FPQ9OjcfQJah5Hnfzau/UTMzaa0ZmmhsNjF+4LxckBK2LLkFmBWWfSmD+cTwfgc5SuYOVMnXUydTvaLmC9nYxpG5QvClCHAh1uOLpSN0lQ8Z/l5nXO4FN9ezxBev8i3k+6ErvQ1c9mAazSlEFEE4nsgeSUxkHTUi0PTx26Wl2+dr6zkSl93OFXcl1MRIesyTTO2FGtwQ/dHMofGFmh1beDz6KSWD/urDD7hWka/r789TKOi8cV3PNMjubv5CTP1StocHZY7y4hdfMskSeP8froOR2XbIhctWqu2T1ZGBM2/3lzv/n69FLtVkqygZOsMubOEyAjNjsemoAnpenCpaMeoeW0a53opt2kBX/nE2KqtRPwwmuAVsBduyHVdraUrSOeGKFEO8Ymyd3P9dxncN6P5lC3CcgJ64sqE0HO+IUmbCk0X8TKtLk6UTbADNtCR50GSuvmP6Yp0S+38AZVRvtItvTIvoXrrV4p46Twz/Czc/W+LVyuCqcdiC1HNDgmSCy8vJKJwX3IUB6vImf6Y3tNckqaJXuAYo/790mGjNjV2e0VMWEPv8SQosmnTCt5/uYtwAhFVjQk=
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
